package Main;

import com.sun.awt.AWTUtilities;
import java.awt.BorderLayout;
import java.awt.CardLayout;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Frame;
import static java.lang.System.exit;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import javax.swing.ButtonGroup;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartPanel;
import org.jfree.chart.JFreeChart;
import org.jfree.data.general.DefaultPieDataset;

public class Home extends javax.swing.JFrame {

    public static int codigoDefault;
    CardLayout cardLayout;
    Color defaultColor, selectedColor;
    int x, y;
    
    //Arreglos JComboBox
    String[] semestres = {"Primero","Segundo","Tercero","Cuarto","Quinto","Sexto","Septimo","Octavo","Noveno","Decimo"};
    String[] carreras = {"IME", "IMA", "IAS","ITS","IMT"};
     
    ButtonGroup btnGr;
    public static String nombreUsuario;
    public static int matriculaUsuario;
    public Home() {
        initComponents();
        AWTUtilities.setWindowOpaque(this, false);
        cargarTabla();
        
        cardLayout = (CardLayout)(panelCards.getLayout());
        defaultColor = new Color(33,33,33);
        selectedColor = new Color(50,50,50);
        elemento1.setBackground(defaultColor);
        
        txtWelcome.setText("Bienvenido, "+nombreUsuario);
        
        btnGr = new ButtonGroup();
        btnGr.add(rbMasculino);
        btnGr.add(rbFemenino);
        
        DefaultComboBoxModel<String> modelSemestres = new DefaultComboBoxModel<>(semestres);
        cm_semestre.setModel(modelSemestres);
      
        DefaultComboBoxModel<String> modelCarreras = new DefaultComboBoxModel<>(carreras);
        cm_carrera.setModel(modelCarreras);
        
        cargarEstadisticas();
                                
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        barLeftBlack = new javax.swing.JPanel();
        elemento1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        elemento2 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        elemento3 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        elemento5 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        panelCards = new javax.swing.JPanel();
        card1 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        txtWelcome = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        card2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblAlumnos = new javax.swing.JTable();
        txtNombre = new javax.swing.JTextField();
        txtEmail = new javax.swing.JTextField();
        txtEdad = new javax.swing.JTextField();
        rbMasculino = new javax.swing.JRadioButton();
        rbFemenino = new javax.swing.JRadioButton();
        txtNumero = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel22 = new javax.swing.JLabel();
        btnGuardar = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        btnLimpiar = new javax.swing.JButton();
        txtApellido = new javax.swing.JTextField();
        jLabel28 = new javax.swing.JLabel();
        cm_carrera = new javax.swing.JComboBox<>();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        cm_semestre = new javax.swing.JComboBox<>();
        txt_id = new javax.swing.JTextField();
        btnLimpiar1 = new javax.swing.JButton();
        card3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        semestre_panel = new javax.swing.JPanel();
        carrera_panel = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        btnActualizar = new javax.swing.JButton();
        panelRoundPersonalizedO1 = new Classes.PanelRoundPersonalizedO();
        panelRoundPersonalizedO4 = new Classes.PanelRoundPersonalizedO();
        button1 = new Classes.Button();
        button2 = new Classes.Button();
        moveIcon = new javax.swing.JLabel();
        panelRoundPersonalizedO2 = new Classes.PanelRoundPersonalizedO();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setMinimumSize(new java.awt.Dimension(1440, 982));
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(1440, 982));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        barLeftBlack.setBackground(new java.awt.Color(33, 33, 33));
        barLeftBlack.setForeground(new java.awt.Color(255, 255, 255));
        barLeftBlack.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        elemento1.setBackground(new java.awt.Color(33, 33, 33));
        elemento1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        elemento1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        elemento1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                elemento1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                elemento1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                elemento1MouseExited(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                elemento1MouseReleased(evt);
            }
        });
        elemento1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                elemento1KeyPressed(evt);
            }
        });
        elemento1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/iconmonstr-home-6-32.png"))); // NOI18N
        elemento1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, -1, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Menu Principal");
        elemento1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 20, 130, 30));
        jLabel4.getAccessibleContext().setAccessibleName("");

        barLeftBlack.add(elemento1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 180, 260, 71));

        elemento2.setBackground(new java.awt.Color(33, 33, 33));
        elemento2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        elemento2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        elemento2.setPreferredSize(new java.awt.Dimension(280, 52));
        elemento2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                elemento2MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                elemento2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                elemento2MouseExited(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                elemento2MouseReleased(evt);
            }
        });
        elemento2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                elemento2KeyPressed(evt);
            }
        });
        elemento2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/iconmonstr-user-31-32 (1).png"))); // NOI18N
        elemento2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, -1, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Alumnos");
        elemento2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 20, 130, 30));

        barLeftBlack.add(elemento2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 260, 260, 70));

        elemento3.setBackground(new java.awt.Color(33, 33, 33));
        elemento3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        elemento3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        elemento3.setMinimumSize(new java.awt.Dimension(280, 52));
        elemento3.setPreferredSize(new java.awt.Dimension(280, 52));
        elemento3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                elemento3MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                elemento3MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                elemento3MouseExited(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                elemento3MouseReleased(evt);
            }
        });
        elemento3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                elemento3KeyPressed(evt);
            }
        });
        elemento3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/iconmonstr-chart-1-32.png"))); // NOI18N
        elemento3.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, -1, -1));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Estadisticas");
        elemento3.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 10, 130, 40));

        barLeftBlack.add(elemento3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 340, 260, 70));
        barLeftBlack.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 430, 220, 10));

        elemento5.setBackground(new java.awt.Color(33, 33, 33));
        elemento5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        elemento5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        elemento5.setMinimumSize(new java.awt.Dimension(280, 52));
        elemento5.setPreferredSize(new java.awt.Dimension(280, 52));
        elemento5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                elemento5MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                elemento5MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                elemento5MouseExited(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                elemento5MouseReleased(evt);
            }
        });
        elemento5.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                elemento5KeyPressed(evt);
            }
        });
        elemento5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/iconmonstr-log-out-1-32.png"))); // NOI18N
        elemento5.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, -1, -1));

        jLabel12.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Salir");
        elemento5.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 20, 60, 30));

        barLeftBlack.add(elemento5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 820, 260, 80));

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/iconmonstr-database-5-72.png"))); // NOI18N
        barLeftBlack.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 30, -1, 62));

        jLabel16.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 24)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 213, 0));
        jLabel16.setText("DATABASE");
        barLeftBlack.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 100, 140, 20));

        jLabel17.setFont(new java.awt.Font("Microsoft YaHei", 0, 20)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 213, 0));
        jLabel17.setText("CLOUD");
        barLeftBlack.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 130, 70, 20));

        getContentPane().add(barLeftBlack, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 260, 900));

        panelCards.setLayout(new java.awt.CardLayout());

        card1.setBackground(new java.awt.Color(51, 51, 51));

        jPanel1.setBackground(new java.awt.Color(25, 25, 25));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtWelcome.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 36)); // NOI18N
        txtWelcome.setForeground(new java.awt.Color(255, 255, 255));
        txtWelcome.setText("Bienvenido, Mauricio");
        jPanel1.add(txtWelcome, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 50, 401, 30));

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 204, 0));
        jLabel2.setText("Justo ahora te encuentras como administrador.");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 90, 517, 30));

        jPanel8.setBackground(new java.awt.Color(0, 0, 0));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/wp2468656-university-wallpapers_1.jpg"))); // NOI18N

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel1)
                .addContainerGap(15, Short.MAX_VALUE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel1)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout card1Layout = new javax.swing.GroupLayout(card1);
        card1.setLayout(card1Layout);
        card1Layout.setHorizontalGroup(
            card1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(card1Layout.createSequentialGroup()
                .addGap(63, 63, 63)
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(card1Layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1193, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        card1Layout.setVerticalGroup(
            card1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(card1Layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(23, Short.MAX_VALUE))
        );

        panelCards.add(card1, "card1");

        card2.setBackground(new java.awt.Color(244, 244, 244));

        jPanel3.setBackground(new java.awt.Color(0, 0, 0));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel13.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 36)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Alumnos");
        jPanel3.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 50, 401, 30));

        jLabel14.setBackground(new java.awt.Color(255, 255, 255));
        jLabel14.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 24)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(153, 153, 153));
        jLabel14.setText("Panel de control de registros.");
        jPanel3.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 80, 320, 50));

        tblAlumnos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Matricula", "Nombre", "Apellido", "Email", "Edad", "Sexo", "telefono", "Carrera", "Semestre", "Agregado por", "Fecha Registro"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, true, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblAlumnos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblAlumnosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblAlumnos);

        rbMasculino.setText("Masculino");

        rbFemenino.setText("Femenino");

        jLabel23.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 24)); // NOI18N
        jLabel23.setText("Nombre");

        jLabel24.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 24)); // NOI18N
        jLabel24.setText("Correo Electronico");

        jLabel25.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 24)); // NOI18N
        jLabel25.setText("Sexo:");

        jLabel26.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 24)); // NOI18N
        jLabel26.setText("Numero de telefono");

        jLabel27.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 24)); // NOI18N
        jLabel27.setText("Edad");

        jPanel2.setBackground(new java.awt.Color(33, 33, 33));

        jLabel22.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 36)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(255, 255, 255));
        jLabel22.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel22.setText("Datos");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel22, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 62, Short.MAX_VALUE)
        );

        btnGuardar.setText("Guardad");
        btnGuardar.setBorderPainted(false);
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        jButton2.setText("Modificar");
        jButton2.setBorderPainted(false);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        btnEliminar.setText("Eliminar");
        btnEliminar.setBorderPainted(false);
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        btnLimpiar.setText("Limpiar");
        btnLimpiar.setBorderPainted(false);
        btnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarActionPerformed(evt);
            }
        });

        jLabel28.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 24)); // NOI18N
        jLabel28.setText("Apellido");

        cm_carrera.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cm_carrera.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cm_carreraActionPerformed(evt);
            }
        });

        jLabel29.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 24)); // NOI18N
        jLabel29.setText("Semestre");

        jLabel30.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 24)); // NOI18N
        jLabel30.setText("Carrera");

        cm_semestre.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        txt_id.setEditable(false);
        txt_id.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_idActionPerformed(evt);
            }
        });

        btnLimpiar1.setText("Actualizar");
        btnLimpiar1.setBorderPainted(false);
        btnLimpiar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiar1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout card2Layout = new javax.swing.GroupLayout(card2);
        card2.setLayout(card2Layout);
        card2Layout.setHorizontalGroup(
            card2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, card2Layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addGroup(card2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(card2Layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 719, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(38, 38, 38)
                        .addGroup(card2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(card2Layout.createSequentialGroup()
                                .addGroup(card2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel23)
                                    .addGroup(card2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jLabel26, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(txtNumero, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jLabel24)
                                    .addGroup(card2Layout.createSequentialGroup()
                                        .addGap(10, 10, 10)
                                        .addGroup(card2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 344, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(btnGuardar)
                                            .addGroup(card2Layout.createSequentialGroup()
                                                .addComponent(jButton2)
                                                .addGap(18, 18, 18)
                                                .addComponent(btnEliminar)
                                                .addGap(18, 18, 18)
                                                .addComponent(btnLimpiar)
                                                .addGap(18, 18, 18)
                                                .addComponent(btnLimpiar1))
                                            .addGroup(card2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addComponent(txt_id, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGroup(card2Layout.createSequentialGroup()
                                                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addGap(18, 18, 18)
                                                    .addGroup(card2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(jLabel28)
                                                        .addGroup(card2Layout.createSequentialGroup()
                                                            .addGap(10, 10, 10)
                                                            .addComponent(txtApellido, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE))))))))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, card2Layout.createSequentialGroup()
                                .addGroup(card2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(card2Layout.createSequentialGroup()
                                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addGroup(card2Layout.createSequentialGroup()
                                        .addGroup(card2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(card2Layout.createSequentialGroup()
                                                .addGroup(card2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addGroup(card2Layout.createSequentialGroup()
                                                        .addComponent(jLabel27)
                                                        .addGap(0, 0, Short.MAX_VALUE))
                                                    .addGroup(card2Layout.createSequentialGroup()
                                                        .addGap(10, 10, 10)
                                                        .addComponent(txtEdad)))
                                                .addGap(18, 18, 18))
                                            .addGroup(card2Layout.createSequentialGroup()
                                                .addGap(10, 10, 10)
                                                .addGroup(card2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jLabel30)
                                                    .addComponent(cm_carrera, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                        .addGroup(card2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel25)
                                            .addGroup(card2Layout.createSequentialGroup()
                                                .addComponent(rbMasculino)
                                                .addGap(18, 18, 18)
                                                .addComponent(rbFemenino))
                                            .addComponent(jLabel29)
                                            .addComponent(cm_semestre, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGap(23, 23, 23))))
                    .addGroup(card2Layout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 1180, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );
        card2Layout.setVerticalGroup(
            card2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(card2Layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addGroup(card2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 668, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(card2Layout.createSequentialGroup()
                        .addGroup(card2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(card2Layout.createSequentialGroup()
                                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(36, 36, 36))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, card2Layout.createSequentialGroup()
                                .addComponent(txt_id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(11, 11, 11)))
                        .addGroup(card2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(card2Layout.createSequentialGroup()
                                .addComponent(jLabel23)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(card2Layout.createSequentialGroup()
                                .addComponent(jLabel28)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtApellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(16, 16, 16)
                        .addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(card2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(card2Layout.createSequentialGroup()
                                .addComponent(jLabel25)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(card2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(rbMasculino)
                                    .addComponent(rbFemenino)))
                            .addGroup(card2Layout.createSequentialGroup()
                                .addComponent(jLabel27)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtEdad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel26)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtNumero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29)
                        .addGroup(card2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel29)
                            .addComponent(jLabel30))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(card2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cm_carrera, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cm_semestre, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(24, 24, 24)
                        .addComponent(btnGuardar)
                        .addGap(30, 30, 30)
                        .addGroup(card2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton2)
                            .addComponent(btnEliminar)
                            .addComponent(btnLimpiar)
                            .addComponent(btnLimpiar1))))
                .addContainerGap(26, Short.MAX_VALUE))
        );

        panelCards.add(card2, "card2");

        card3.setBackground(new java.awt.Color(244, 244, 244));
        card3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel4.setBackground(new java.awt.Color(0, 0, 0));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel18.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 36)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText("Estadisticas");
        jPanel4.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 50, 401, 30));

        jLabel19.setBackground(new java.awt.Color(255, 255, 255));
        jLabel19.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 24)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(153, 153, 153));
        jLabel19.setText("Este es el panel de administracion y estadisticas.");
        jPanel4.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 80, 517, 50));

        card3.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1180, 180));

        semestre_panel.setBackground(new java.awt.Color(204, 204, 204));

        javax.swing.GroupLayout semestre_panelLayout = new javax.swing.GroupLayout(semestre_panel);
        semestre_panel.setLayout(semestre_panelLayout);
        semestre_panelLayout.setHorizontalGroup(
            semestre_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 500, Short.MAX_VALUE)
        );
        semestre_panelLayout.setVerticalGroup(
            semestre_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 500, Short.MAX_VALUE)
        );

        card3.add(semestre_panel, new org.netbeans.lib.awtextra.AbsoluteConstraints(58, 274, -1, 500));

        carrera_panel.setBackground(new java.awt.Color(204, 204, 204));

        javax.swing.GroupLayout carrera_panelLayout = new javax.swing.GroupLayout(carrera_panel);
        carrera_panel.setLayout(carrera_panelLayout);
        carrera_panelLayout.setHorizontalGroup(
            carrera_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 500, Short.MAX_VALUE)
        );
        carrera_panelLayout.setVerticalGroup(
            carrera_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 500, Short.MAX_VALUE)
        );

        card3.add(carrera_panel, new org.netbeans.lib.awtextra.AbsoluteConstraints(604, 274, -1, -1));

        btnActualizar.setText("Actualizar");
        btnActualizar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnActualizarMouseClicked(evt);
            }
        });
        btnActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addComponent(btnActualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(865, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(btnActualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        card3.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 180, 1180, 80));

        panelCards.add(card3, "card3");

        getContentPane().add(panelCards, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 50, 1180, 900));

        panelRoundPersonalizedO1.setBackground(new java.awt.Color(20, 20, 20));
        panelRoundPersonalizedO1.setRoundTopLeft(25);
        panelRoundPersonalizedO1.setRoundTopRight(25);

        panelRoundPersonalizedO4.setBackground(new java.awt.Color(205, 217, 115));
        panelRoundPersonalizedO4.setPreferredSize(new java.awt.Dimension(78, 37));
        panelRoundPersonalizedO4.setRoundTopLeft(25);
        panelRoundPersonalizedO4.setRoundTopRight(25);

        button1.setBackground(new java.awt.Color(242, 5, 25));
        button1.setPreferredSize(new java.awt.Dimension(25, 25));
        button1.setSelectedColor(new java.awt.Color(89, 2, 2));
        button1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                button1MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout button1Layout = new javax.swing.GroupLayout(button1);
        button1.setLayout(button1Layout);
        button1Layout.setHorizontalGroup(
            button1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 25, Short.MAX_VALUE)
        );
        button1Layout.setVerticalGroup(
            button1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 25, Short.MAX_VALUE)
        );

        button2.setBackground(new java.awt.Color(44, 217, 17));
        button2.setPreferredSize(new java.awt.Dimension(25, 25));
        button2.setSelectedColor(new java.awt.Color(15, 80, 6));
        button2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                button2MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout button2Layout = new javax.swing.GroupLayout(button2);
        button2.setLayout(button2Layout);
        button2Layout.setHorizontalGroup(
            button2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 25, Short.MAX_VALUE)
        );
        button2Layout.setVerticalGroup(
            button2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 25, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout panelRoundPersonalizedO4Layout = new javax.swing.GroupLayout(panelRoundPersonalizedO4);
        panelRoundPersonalizedO4.setLayout(panelRoundPersonalizedO4Layout);
        panelRoundPersonalizedO4Layout.setHorizontalGroup(
            panelRoundPersonalizedO4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelRoundPersonalizedO4Layout.createSequentialGroup()
                .addContainerGap(10, Short.MAX_VALUE)
                .addComponent(button2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(button1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12))
        );
        panelRoundPersonalizedO4Layout.setVerticalGroup(
            panelRoundPersonalizedO4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelRoundPersonalizedO4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panelRoundPersonalizedO4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(button2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(button1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        moveIcon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        moveIcon.setCursor(new java.awt.Cursor(java.awt.Cursor.MOVE_CURSOR));
        moveIcon.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                moveIconMouseDragged(evt);
            }
        });
        moveIcon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                moveIconMousePressed(evt);
            }
        });

        javax.swing.GroupLayout panelRoundPersonalizedO1Layout = new javax.swing.GroupLayout(panelRoundPersonalizedO1);
        panelRoundPersonalizedO1.setLayout(panelRoundPersonalizedO1Layout);
        panelRoundPersonalizedO1Layout.setHorizontalGroup(
            panelRoundPersonalizedO1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelRoundPersonalizedO1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(moveIcon, javax.swing.GroupLayout.DEFAULT_SIZE, 1344, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelRoundPersonalizedO4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        panelRoundPersonalizedO1Layout.setVerticalGroup(
            panelRoundPersonalizedO1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelRoundPersonalizedO1Layout.createSequentialGroup()
                .addContainerGap(7, Short.MAX_VALUE)
                .addGroup(panelRoundPersonalizedO1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(panelRoundPersonalizedO4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(moveIcon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        getContentPane().add(panelRoundPersonalizedO1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1440, 50));

        panelRoundPersonalizedO2.setBackground(new java.awt.Color(20, 20, 20));
        panelRoundPersonalizedO2.setRoundBottomLeft(25);
        panelRoundPersonalizedO2.setRoundBottomRight(25);

        javax.swing.GroupLayout panelRoundPersonalizedO2Layout = new javax.swing.GroupLayout(panelRoundPersonalizedO2);
        panelRoundPersonalizedO2.setLayout(panelRoundPersonalizedO2Layout);
        panelRoundPersonalizedO2Layout.setHorizontalGroup(
            panelRoundPersonalizedO2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1440, Short.MAX_VALUE)
        );
        panelRoundPersonalizedO2Layout.setVerticalGroup(
            panelRoundPersonalizedO2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );

        getContentPane().add(panelRoundPersonalizedO2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 950, 1440, 30));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void elemento1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_elemento1KeyPressed
       
    }//GEN-LAST:event_elemento1KeyPressed

    private void elemento1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_elemento1MouseClicked
        cardLayout.show(panelCards, "card1"); 
    }//GEN-LAST:event_elemento1MouseClicked

    private void elemento1MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_elemento1MouseReleased
        
    }//GEN-LAST:event_elemento1MouseReleased

    private void elemento1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_elemento1MouseEntered
        elemento1.setBackground(selectedColor);
    }//GEN-LAST:event_elemento1MouseEntered

    private void elemento1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_elemento1MouseExited
        elemento1.setBackground(defaultColor);
    }//GEN-LAST:event_elemento1MouseExited

    private void elemento2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_elemento2MouseClicked
        cardLayout.show(panelCards, "card2"); 
    }//GEN-LAST:event_elemento2MouseClicked

    private void elemento2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_elemento2MouseEntered
        elemento2.setBackground(selectedColor);
    }//GEN-LAST:event_elemento2MouseEntered

    private void elemento2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_elemento2MouseExited
        elemento2.setBackground(defaultColor);
    }//GEN-LAST:event_elemento2MouseExited

    private void elemento2MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_elemento2MouseReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_elemento2MouseReleased

    private void elemento2KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_elemento2KeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_elemento2KeyPressed

    private void elemento3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_elemento3MouseClicked
        cardLayout.show(panelCards, "card3"); 
    }//GEN-LAST:event_elemento3MouseClicked

    private void elemento3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_elemento3MouseEntered
        elemento3.setBackground(selectedColor);
    }//GEN-LAST:event_elemento3MouseEntered

    private void elemento3MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_elemento3MouseExited
        elemento3.setBackground(defaultColor);
    }//GEN-LAST:event_elemento3MouseExited

    private void elemento3MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_elemento3MouseReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_elemento3MouseReleased

    private void elemento3KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_elemento3KeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_elemento3KeyPressed

    private void elemento5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_elemento5MouseClicked
        System.exit(0); //Salir
    }//GEN-LAST:event_elemento5MouseClicked

    private void elemento5MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_elemento5MouseEntered
        elemento5.setBackground(selectedColor);
    }//GEN-LAST:event_elemento5MouseEntered

    private void elemento5MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_elemento5MouseExited
        elemento5.setBackground(defaultColor);
    }//GEN-LAST:event_elemento5MouseExited

    private void elemento5MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_elemento5MouseReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_elemento5MouseReleased

    private void elemento5KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_elemento5KeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_elemento5KeyPressed

    private void moveIconMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_moveIconMousePressed
        x = evt.getX();
        y = evt.getY();
    }//GEN-LAST:event_moveIconMousePressed

    private void moveIconMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_moveIconMouseDragged
        this.setLocation(this.getLocation().x + evt.getX() - x, this.getLocation().y + evt.getY() - y);
    }//GEN-LAST:event_moveIconMouseDragged
    
    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
    
        String nombre = txtNombre.getText();
        String apellido = txtApellido.getText();
        String email = txtEmail.getText();
        int edad = Integer.parseInt(txtEdad.getText());
        String numero = txtNumero.getText();
        
        String carrera = (String) cm_carrera.getSelectedItem();
        String semestre = (String) cm_semestre.getSelectedItem();
        int agregadoPor = matriculaUsuario;
        
        String sexo;
        
        if(rbMasculino.isSelected() == true){
            sexo = "M";
        } else if(rbFemenino.isSelected() == true){
            sexo = "F";
            
        } else {
            sexo = "M";
        }
        
        try {
            Connection con = Conexion.getConexion();
            PreparedStatement ps = con.prepareStatement("INSERT INTO alumnos (nombre, apellido, email, edad, sexo, numero_telefono, carrera, semestre, agregado_por) VALUES (?,?,?,?,?,?,?,?,?)");
            ps.setString(1, nombre);
            ps.setString(2, apellido);
            ps.setString(3, email);
            ps.setInt(4, edad);
            ps.setString(5, sexo);
            ps.setString(6, numero);
            ps.setString(7, carrera);
            ps.setString(8, semestre);
            ps.setInt(9, agregadoPor);
         
            ps.executeUpdate();
            JOptionPane.showMessageDialog(null, "Registro Exitoso");
            limpiar();
            cargarTabla();
        } catch (SQLException e) {
            if (e.getSQLState().startsWith("23")) {
                // Error de duplicado en campo UNIQUE
                JOptionPane.showMessageDialog(null, "Email Existente.");
            } else {
                // Otro tipo de error
                JOptionPane.showMessageDialog(null, e.toString());
            }
        }
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void cm_carreraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cm_carreraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cm_carreraActionPerformed

    private void tblAlumnosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblAlumnosMouseClicked
        //
            try {
                // Obtener fila seleccionada
                int filaSeleccionada = tblAlumnos.getSelectedRow();
    
                if (filaSeleccionada == -1) {
                    JOptionPane.showMessageDialog(null, "Seleccione un registro para eliminar.");
                    return;
                }
    
                // Obtener id del registro seleccionado
                int id = Integer.parseInt(tblAlumnos.getValueAt(filaSeleccionada, 0).toString());
                PreparedStatement ps;
                ResultSet rs;
        
                Connection con = Conexion.getConexion();
                ps = con.prepareStatement("SELECT id, nombre, apellido, email, edad, sexo, numero_telefono, carrera, semestre FROM alumnos WHERE id = ?");
                ps.setInt(1, id);
                rs = ps.executeQuery();
            
            while(rs.next()){
                txt_id.setText(String.valueOf(rs.getInt("id")));
                txtNombre.setText(rs.getString("nombre"));
                txtApellido.setText(rs.getString("apellido"));
                txtEmail.setText(rs.getString("email"));
                txtEdad.setText(rs.getString("edad"));
                txtNumero.setText(rs.getString("numero_telefono"));
                
                String txtCarrera = rs.getString("carrera");
                String txtSemestre = rs.getString("semestre");
                
                // Asignar JComboBox en base al registro carrera
                for (int i = 0; i < carreras.length; i++) {
                    String item = carreras[i];
                    if (item.equals(txtCarrera)) {
                        cm_carrera.setSelectedIndex(i);
                        break;
                    }
                }
                
                // Asignar JComboBox en base al registro semestre
                for (int i = 0; i < semestres.length; i++) {
                    String item = semestres[i];
                    if (item.equals(txtSemestre)) {
                        cm_semestre.setSelectedIndex(i);
                        break;
                    }
                }
        
                if(rs.getString("sexo").equals("M")){
                    rbMasculino.setSelected(true);
                }else if(rs.getString("sexo").equals("F")){
                    rbFemenino.setSelected(true);
                }
            }
            
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, e.toString());
        }
        
        
        
        //COMENTARIO DE LA TAAAAAAAABLA
    }//GEN-LAST:event_tblAlumnosMouseClicked

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        
        // Obtener fila seleccionada
        int filaSeleccionada = tblAlumnos.getSelectedRow();
    
        if (filaSeleccionada == -1) {
            JOptionPane.showMessageDialog(null, "Seleccione un registro para eliminar.");
            return;
        }
    
        // Obtener id del registro seleccionado
        int id = Integer.parseInt(tblAlumnos.getValueAt(filaSeleccionada, 0).toString());
        
        String nombre = txtNombre.getText();
        String apellido = txtApellido.getText();
        String email = txtEmail.getText();
        int edad = Integer.parseInt(txtEdad.getText());
        String numero = txtNumero.getText();
        
        String carrera = (String) cm_carrera.getSelectedItem();
        String semestre = (String) cm_semestre.getSelectedItem();
        
        String sexo;
        if(rbMasculino.isSelected() == true){
            sexo = "M";
        } else if(rbFemenino.isSelected() == true){
            sexo = "F";
            
        } else {
            sexo = "M";
        }
        
        try {
        
            Connection con = Conexion.getConexion();
            PreparedStatement ps = con.prepareStatement("UPDATE alumnos SET nombre = ?, apellido = ?, email = ?, edad = ?, sexo = ?, numero_telefono = ?, carrera = ?, semestre = ? WHERE id = ?");
            ps.setString(1, nombre);
            ps.setString(2, apellido);
            ps.setString(3, email);
            ps.setInt(4, edad);
            ps.setString(5, sexo);
            ps.setString(6, numero);
            ps.setString(7, carrera);
            ps.setString(8, semestre);
            ps.setInt(9, id);
         
            ps.executeUpdate();
            JOptionPane.showMessageDialog(null, "Modificacion Exitosa.");
            limpiar();
            cargarTabla();
        } catch (SQLException e) {
            if (e.getSQLState().startsWith("23")) {
                // Error de duplicado en campo UNIQUE
                JOptionPane.showMessageDialog(null, "Email Existente.");
            } else {
                // Otro tipo de error
                JOptionPane.showMessageDialog(null, e.toString());
            }
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        
        //ELIMINAR
        // Obtener fila seleccionada
        int filaSeleccionada = tblAlumnos.getSelectedRow();
    
        if (filaSeleccionada == -1) {
            JOptionPane.showMessageDialog(null, "Seleccione un registro para eliminar.");
            return;
        }
    
        // Obtener id del registro seleccionado
        int id = Integer.parseInt(tblAlumnos.getValueAt(filaSeleccionada, 0).toString());
        
        try {
            Connection con = Conexion.getConexion();
            PreparedStatement ps = con.prepareStatement("DELETE FROM alumnos WHERE id = ?");
            ps.setInt(1, id);
            ps.executeUpdate();
            JOptionPane.showMessageDialog(null, "Registro Eliminado.");
            limpiar();
            cargarTabla();
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, e.toString());
        }
        
        
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed
        // LIMPIAR
        limpiar();
    }//GEN-LAST:event_btnLimpiarActionPerformed

    private void txt_idActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_idActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_idActionPerformed

    private void btnActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarActionPerformed
        cargarEstadisticas();
    }//GEN-LAST:event_btnActualizarActionPerformed

    private void btnLimpiar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiar1ActionPerformed
        cargarTabla();
    }//GEN-LAST:event_btnLimpiar1ActionPerformed

    private void button1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_button1MouseClicked
        dispose();
    }//GEN-LAST:event_button1MouseClicked

    private void button2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_button2MouseClicked
        setState(Frame.ICONIFIED);
    }//GEN-LAST:event_button2MouseClicked

    private void btnActualizarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnActualizarMouseClicked
        cargarEstadisticas();
        cargarTabla();
    }//GEN-LAST:event_btnActualizarMouseClicked

    private void limpiar(){
        
        txt_id.setText("");
        txtNombre.setText("");
        txtApellido.setText("");
        txtEmail.setText("");
        txtEdad.setText("");
        txtNumero.setText("");
        btnGr.clearSelection();
        
        // Reiniciar o restablecer el JComboBox
        cm_carrera.setSelectedIndex(0);
        // Reiniciar o restablecer el JComboBox
        cm_semestre.setSelectedIndex(0);
        
        //Desactivar selecion de registro
        tblAlumnos.clearSelection();
        
    }
    
    private void cargarTabla(){
        
        DefaultTableModel modelTabla = (DefaultTableModel) tblAlumnos.getModel();
        modelTabla.setRowCount(0);
        
        PreparedStatement ps;
        ResultSet rs;
        ResultSetMetaData rsmd;
        int columnas;
        
        try{
            Connection con = Conexion.getConexion();
            ps = con.prepareStatement("SELECT id, nombre, apellido, email, edad, sexo, numero_telefono, carrera, semestre, agregado_por,fecha_registro FROM alumnos");
            rs = ps.executeQuery();
            rsmd = rs.getMetaData();
            columnas = rsmd.getColumnCount();
            
            while(rs.next()){
                Object[] fila = new Object[columnas];
                for(int indice = 0; indice < columnas; indice++){
                   fila[indice] = rs.getObject(indice + 1);
                }
                modelTabla.addRow(fila);
            }
            
        }catch(SQLException e){
            JOptionPane.showMessageDialog(null, e.toString());
        }
    }
    
    private void cargarEstadisticas(){
        
        //Variables de conexion
        PreparedStatement ps;
        ResultSet rs;
        
        //Variables JCmoboBox
        String txtCarrera;
        String txtSemestre;
        int indiceCarrera;
        int indiceSemestre;
        
        //Contadores
        int[] countCarrera = {0,0,0,0,0};
        int[] countSemestre = {0,0,0,0,0,0,0,0,0,0};
        
        //carreras = {"IME", "IMA", "IAS","ITS","IMT"};
        //semestres = {"Primero","Segundo","Tercero","Cuarto","Quinto","Sexto","Septimo","Octavo","Noveno","Decimo"};
        
        try{
            Connection con = Conexion.getConexion();
            ps = con.prepareStatement("SELECT carrera, semestre FROM alumnos");
            rs = ps.executeQuery();
            
            while(rs.next()){
                //Obtener textos de registros
                txtCarrera = rs.getString("carrera");
                txtSemestre = rs.getString("semestre");
            
                //Obtener elemento de JForm
                DefaultComboBoxModel<String> carrera = (DefaultComboBoxModel<String>) cm_carrera.getModel();
                DefaultComboBoxModel<String> semestre = (DefaultComboBoxModel<String>) cm_semestre.getModel();

                //En base al registro, obtener indice de item
                indiceCarrera = carrera.getIndexOf(txtCarrera);
                indiceSemestre = semestre.getIndexOf(txtSemestre);
            
                countCarrera[indiceCarrera]++;
                countSemestre[indiceSemestre]++;
            }
        }catch(SQLException e){
            JOptionPane.showMessageDialog(null, e.toString());
        }
        
        //Imprimir Graficas
        
        //SEMESTRES
        DefaultPieDataset datos = new DefaultPieDataset();
        for(int i = 0; i < 10; i++){
            datos.setValue("Semestre " + (i+1), countSemestre[i]);
        }
        
        JFreeChart grafico_circular = ChartFactory.createPieChart(
                "Alumnos Por Semestre", 
                datos, 
                true, 
                true, 
                false);
        
        ChartPanel panel = new ChartPanel(grafico_circular);
        panel.setMouseWheelEnabled(true);
        panel.setPreferredSize(new Dimension(500,500));
        
        semestre_panel.setLayout(new BorderLayout());
        semestre_panel.add(panel,BorderLayout.NORTH);
        
        ///////////////////////////////////////////////////////
        
        //CARRERAS
        DefaultPieDataset datos2 = new DefaultPieDataset();
        
        datos2.setValue("IME", countCarrera[0]);
        datos2.setValue("IMA", countCarrera[1]);
        datos2.setValue("IAS", countCarrera[2]);
        datos2.setValue("ITS", countCarrera[3]);
        datos2.setValue("IMT", countCarrera[4]);
        
        JFreeChart grafico_circular2 = ChartFactory.createPieChart(
                "Carreras Seleccionadas Por Alumnos", 
                datos2, 
                true, 
                true, 
                false);
        
        ChartPanel panel2 = new ChartPanel(grafico_circular2);
        panel2.setMouseWheelEnabled(true);
        panel2.setPreferredSize(new Dimension(500,500));
        
        carrera_panel.setLayout(new BorderLayout());
        carrera_panel.add(panel2,BorderLayout.NORTH);
        
        pack();
        repaint();
        
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Home().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel barLeftBlack;
    private javax.swing.JButton btnActualizar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JButton btnLimpiar1;
    private Classes.Button button1;
    private Classes.Button button2;
    private javax.swing.JPanel card1;
    private javax.swing.JPanel card2;
    private javax.swing.JPanel card3;
    private javax.swing.JPanel carrera_panel;
    private javax.swing.JComboBox<String> cm_carrera;
    private javax.swing.JComboBox<String> cm_semestre;
    private javax.swing.JPanel elemento1;
    private javax.swing.JPanel elemento2;
    private javax.swing.JPanel elemento3;
    private javax.swing.JPanel elemento5;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel moveIcon;
    private javax.swing.JPanel panelCards;
    private Classes.PanelRoundPersonalizedO panelRoundPersonalizedO1;
    private Classes.PanelRoundPersonalizedO panelRoundPersonalizedO2;
    private Classes.PanelRoundPersonalizedO panelRoundPersonalizedO4;
    private javax.swing.JRadioButton rbFemenino;
    private javax.swing.JRadioButton rbMasculino;
    private javax.swing.JPanel semestre_panel;
    private javax.swing.JTable tblAlumnos;
    private javax.swing.JTextField txtApellido;
    private javax.swing.JTextField txtEdad;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtNumero;
    private javax.swing.JLabel txtWelcome;
    private javax.swing.JTextField txt_id;
    // End of variables declaration//GEN-END:variables
}
